# NumPy Exercise (5 points)

Create a 2x10 array (two rows and 10 columns) `ary0` of 10 zeros, using integer numbers as data type. 

In [1]:
# Your code here
import numpy as np
ary0 = np.zeros((2, 10),dtype=np.int)

Create an array `ary1` of 10 ones using float numbers, and an array `aray3` of 10 threes using integer numbers. Concatenate the three arrays (ary0, ary1,ary3) horiztonally to obtain a 4x10 array called `ary4`.

In [2]:
# Your code here
ary1 = np.ones((1, 10), dtype=float)
ary3 = np.ones((1, 10), dtype=int) * 3
ary4 = np.concatenate((ary0, ary1, ary3), axis=0)

Display the data type of `ary4`. Why it is that data type?

In [3]:
# Your code here
print(ary4)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]]


Create a numpy array of integers from 10 to 50.

In [4]:
# Your code here
ary = np.arange(10, 51, dtype=int)
ary

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create a numpy array of the "even" integers from 5 to 29.

In [5]:
# Your code here
even = np.arange(5, 30, 2, dtype=int)
even

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

Create a 3x4 array with values ranging from 0 to 12, using `arange` and `reshape`.

In [6]:
# Your code here
a2 = np.arange(12).reshape((3, 4))
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Generate an array of 15 random numbers sampled from a standard normal distribution with 3 mean and 12 standard deviation, by applying a Random State to the random number generator. 

In [7]:
# Your code here
np.random.seed(200)
3 + 12*np.random.randn(15)
abc1 = np.random.RandomState(seed=200)
ary11=3+12*abc1.randn(15)
ary11

array([-14.41137899,  25.93143761,  11.54254984,   0.02714056,
         7.33759482,   2.60460395,   0.34383939,   8.72708132,
        -5.30327249,  12.50407117,   3.87898961,  18.6394324 ,
         5.56177788,  15.20818743,  25.94054137])

Display the indices of the elements of the above array sorted in ascending order. 

In [8]:
# Your code here
np.sort(ary11,axis=0)

array([-14.41137899,  -5.30327249,   0.02714056,   0.34383939,
         2.60460395,   3.87898961,   5.56177788,   7.33759482,
         8.72708132,  11.54254984,  12.50407117,  15.20818743,
        18.6394324 ,  25.93143761,  25.94054137])

Generate a 4x5 array called `ary4` of random numbers sampled from a uniform distribution. Use the random seed `12` to ensure reproducibility. 

In [9]:
# Your code here
np.random.seed(12)
ary4 = np.random.randn(4, 5)
print(ary4)

[[ 0.47298583 -0.68142588  0.2424395  -1.70073563  0.75314283]
 [-1.53472134  0.00512708 -0.12022767 -0.80698188  2.87181939]
 [-0.59782292  0.47245699  1.09595612 -1.2151688   1.34235637]
 [-0.12214979  1.01251548 -0.91386915 -1.02953021  1.20979645]]


Display the average values of the rows of `ary4`.

In [10]:
# Your code here
print(ary4.mean(axis=1))

[-0.18271867  0.08300312  0.21955555  0.03135256]


Display the index of the minimum element in each column in `ary4`. 

In [11]:
# Your code here
index = np.argmin(ary4, axis=0)
print(index)

[1 0 3 0 0]


Create a Boolean mask of the elements in `ary4` that are in the range between 0.3 and 0.8, and afterward use the mask to extract the elements into a new array `ary5`.

In [12]:
# Your code here
ary5 = (ary4>=0.3)&(ary4<=0.8)
print(ary5)

[[ True False False False  True]
 [False False False False False]
 [False  True False False False]
 [False False False False False]]


Flatten `ary5` using both `flatten()` and `ravel()` and check if the resulting arrays are views of `ary5` (i.e., share the same memory).

Create an array of 40 linearly spaced points between 3 and 5.

In [13]:
# Your code here
nl = np.linspace(3, 5, 40)

For the given array `mat`, in the following cells apply slicing operations to replicate the displayed outputs.

In [14]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
# Your code here
mat[-3:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [16]:
# Your code here
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [17]:
# Your code here
mat[1:3, [2,4]]

array([[ 8, 10],
       [13, 15]])

In [18]:
# Your code here
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])